{
  backend: {
    name: 'git-gateway',
    branch: 'master'
  },
  media_folder: '/static/files/',
  public_folder: '/files/',
  collections: [
    {
      name: 'blog',
      label: 'Blog',
      folder: 'src/pages/blog',
      create: true,
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}',
      fields: [
        { name: 'contentType', label: 'Content Type', widget: 'hidden', default: 'blog' },
        { name: 'path', label: 'Path', widget: 'string' },
        { name: 'title', label: 'Title', widget: 'string' },
        { name: 'date', label: 'Publish Date', widget: 'datetime' },
        { name: 'body', label: 'Body', widget: 'markdown' },
        {
          name: 'attachments',
          label: 'Attachment',
          widget: 'list',
          default: [],
          fields: [
            { name: 'filename', label: 'Filename', widget: 'file' }
          ]
        },
        {
          name: 'related',
          label: 'Related Post',
          widget: 'list',
          default: [],
          fields: [
            {
              name: 'post',
              label: 'Post',
              widget: 'relation',
              collection: 'blog',
              searchFields: ['name', 'path', 'title'],
              valueField: 'path'
            }
          ]
        }
      ]
    },
    {
      name: 'about',
      label: 'About',
      folder: 'src/pages/about',
      create: false,
      slug: '{{slug}}',
      fields: [
        { name: 'contentType', label: 'Content Type', widget: 'hidden', default: 'about' },
        { name: 'path', label: 'Path', widget: 'hidden', default: '/about' },
        { name: 'title', label: 'Title', widget: 'string' },
        { name: 'body', label: 'Body', widget: 'markdown' }
      ]
    }
  ]
}